name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build WASM
        run: |
          cargo install wasm-pack --version 0.10.3
          wasm-pack build --target web --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: |
            index.html
            style.css
            app.js
            pkg/obit_generator.js
            pkg/obit_generator_bg.wasm
            .nojekyll

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: website
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
