name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build WASM
        run: |
          cargo install wasm-pack --version 0.10.3
          wasm-pack build --target web --release
          cp pkg/obit_generator.js .
          cp pkg/obit_generator_bg.wasm .

      - name: Upload files
        uses: actions/upload-pages-artifact@v2
        with:
          path: |
            index.html
            style.css
            app.js
            obit_generator.js
            obit_generator_bg.wasm
            .nojekyll

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
